collections:
    # A mix of the two until amazon.aws absorbs all the modules required in this repo.
    - name: amazon.aws
      source: https://galaxy.ansible.com
    - name: community.aws
      source: https://galaxy.ansible.com
    - name: community.general
      version: 3.2.0
      source: https://galaxy.ansible.com