collections:
    - name: amazon.aws
      version: 2.0.0
    - name: community.general
      version: 4.0.1
    - name: cisco.ios
      version: 2.5.0
    - name: ansible.netcommon
      version: 2.4.0   