---
- name: Run installation Go module
  include_role:
    name: go

- name: Recursively change ownership of Go's local directory
  file:
    path: "/home/{{ user }}/go"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"