---
# ansible-playbook create-ec2-Fedora.yml -vv

- name: Create EC2 instance
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  vars:
   - ec2_instance_type: t2.micro
   - ec2_ami_id: ami-0285100bb3546c0e7
   - ec2_name_tag: nleiva-fedora-32
   - ec2_ansible_group_tag: Fedora
   - volume:
     - device_name: /dev/sda1
       volume_type: gp2
       volume_size: 30
       delete_on_termination: true

  tasks:
    - name: Create Fedora EC2 instance in AWS
      include_role:
        name: aws_create_ec2