# ansible-playbook create-ec2-Fedora-35.yml -e "ssh_pubkey=..." -v

# Play 1: Create instance on AWS
- name: Create EC2 instance
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  vars_files:
    - ./vars/fedora.yml
    - ./vars/aws_common.yml

  tasks:
    - name: Create Fedora EC2 instance in AWS
      ansible.builtin.include_role:
        name: aws_create_ec2

    - name: Grab facts for the instance(s) we just created
      amazon.aws.ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance-state-name: running
          "tag:Name": "{{ ec2_name_tag }}"
      register: ansible_node_facts

    - name: Set facts for next play
      ansible.builtin.set_fact:
        instance_name: "{{ ec2_name_tag }}"

    - name: Add instance(s) to my_instances group
      ansible.builtin.add_host:
        name: "{{ item.tags.Name }}"
        ansible_host: "{{ item.public_ip_address }}"
        ansible_user: "{{ ec2_username }}"
        private_ip: "{{ item.private_ip_address }}"
        ansible_ssh_private_key_file: "{{ private_key_file }}"
        instance_ssh: "{{ ssh_info }}"
        groups:
          - my_instances
      with_items: "{{ ansible_node_facts.instances }}"

# Play 2: Install packages
- name: Configure Instance(s)
  hosts: "my_instances"
  become: true
  gather_facts: true
  vars_files:
    - ./vars/go_install.yml
    - ./vars/go_vs_code.yml
  vars:
   - epel_repo: epel-release
   - user: fedora

  tasks:
    - name: Display variables/facts known for instance
      ansible.builtin.debug:
        msg: "Running {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }}), IP address: {{ ansible_host }}"

    - name: Install packages and config files
      ansible.builtin.include_role:
        name: configure_instance