
- name: Notify user
  hosts: localhost
  connection: local
  # become: true
  #strategy: free
  #become_method: enable
  gather_facts: true

  tasks:
    - name: Send report e-mail using SendGrid
      community.general.sendgrid:
        api_key: "{{ sendgrid_api_key }}"
        from_address: "{{ sendgrid_from_address }}"
        to_addresses: "{{ sendgrid_to_address }}"
        subject: "{{ sendgrid_email_subject }}"
        body: "{{ Everything looks good }}"
        html_body: true
      #delegate_to: localhost
      #run_once: true
