- name: Provision EC2 instances
  community.aws.ec2_instance:
    name: "{{ ec2_name_tag }}"
    region: "{{ ec2_region }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_ami_id }}"
    key_name: "{{ ec2_resource_prefix }}-key"
    vpc_subnet_id: "{{ create_subnet.subnet.id }}"
    assign_public_ip: true
    group: "{{ ec2_resource_prefix }}-insecure-SG"
    wait: yes
    volumes: "{{ ec2_volume }}"
    tags:
      Environment: "{{ ec2_environment }}"
      Contact: "{{ ec2_contact_tag }}"
  register: ec2

- name: Wait for SSH to come up
  include: try-to-ssh.yml
  with_items: "{{ ec2.instances }}"