- name: Create AWS VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ ec2_resource_prefix }}-vpc"
    cidr_block: "{{ ec2_cidr_block }}"
    region: "{{ ec2_region }}"
    tags:
      Environment: "{{ ec2_environment }}"
  register: create_vpc
  until: create_vpc is not failed
  retries: 5

# - name: Create AWS VPC (NETWORK MODE)
#   amazon.aws.ec2_vpc_net:
#     name: "{{ ec2_resource_prefix }}-net-vpc"
#     cidr_block: "{{ ec2_cidr_block_net }}"
#     region: "{{ ec2_region }}"
#     tags:
#       Environment: "{{ ec2_environment }}"
#   register: create_vpc_net
#   until: create_vpc_net is not failed
#   retries: 5