- name: Create Route Table
  community.aws.ec2_vpc_route_table:
    region: "{{ ec2_region }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    subnets:
      - "{{ create_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
    tags:
      Environment: "{{ ec2_environment }}"
  register: rt_table
  until: rt_table is not failed
  retries: 5

# - name: Create Route Table (NETWORK MODE)
#   community.aws.ec2_vpc_route_table:
#     region: "{{ ec2_region }}"
#     vpc_id: "{{ create_vpc_net.vpc.id }}"
#     subnets:
#       - "{{ create_subnet_net.subnet.id }}"
#     routes:
#       - dest: 0.0.0.0/0
#         gateway_id: "{{ igw_net.gateway_id }}"
#     tags:
#       Environment: "{{ ec2_environment }}"
#   register: rt_table_net
#   until: rt_table_net is not failed
#   retries: 5