- name: Create SSH Key Pair
  ansible.builtin.include_tasks: create_key_pair.yml

- name: Create VPC
  ansible.builtin.include_tasks: create_vpc.yml

- name: Create Security Group
  ansible.builtin.include_tasks: create_security_group.yml

- name: Create Subnet
  ansible.builtin.include_tasks: create_subnet.yml

- name: Create Internet Gateway
  ansible.builtin.include_tasks: create_igw.yml

- name: Create Route Table
  ansible.builtin.include_tasks: create_rt_table.yml

- name: Check AMI
  ansible.builtin.include_tasks: find_ami.yml
  when: my_os is defined

- name: Provision EC2 Instance
  ansible.builtin.include_tasks: create_ec2_instance.yml
