---
- name: Wait until we can SSH to the instance
  wait_for: 
    host: "{{ item.public_ip }}" 
    port: 22 
    state: started
- name: Print the public IP address
  debug:
    msg: "We are able to SSH to {{ item.public_ip }}" 