ec2_region: us-east-1

# Instance variables 
ec2_volume: "{{ volume | default(omit) }}"

ec2_cidr_block: "172.18.0.0/16"
ec2_subnet: "172.18.0.0/24"
ec2_delete_by_tag: "{{ ansible_date_time.date | replace('-','.') }}"
ec2_environment: "{{ ec2_resource_prefix }}"